# Generated by Django 5.2.7 on 2025-10-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(help_text='Duration to next airport in hours')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_node', to='routes.airportroute')),
            ],
        ),
    ]
