# Generated by Django 5.2.7 on 2025-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportroute',
            name='duration',
            field=models.FloatField(),
        ),
    ]
